

export const TYPES = {
    SELECT_ARTICLE: 'SELECT_ARTICLE',


    LOAD_COUNTRIES: 'LOAD_COUNTRIES',
    LOAD_COUNTRIES_STARTED: 'LOAD_COUNTRIES_STARTED',
    LOAD_COUNTRIES_FAILED: 'LOAD_COUNTRIES_FAILED',


    LOAD_LEAGUES: 'LOAD_LEAGUES',
    LOAD_LEAGUES_STARTED: 'LOAD_LEAGUES_STARTED',
    LOAD_LEAGUES_FAILED: 'LOAD_LEAGUES_FAILED',

    LOAD_GAME: 'LOAD_GAME',
    LOAD_GAME_STARTED: 'LOAD_GAME_STARTED',
    LOAD_GAME_FAILED: 'LOAD_GAME_FAILED',
};